# Generated by Django 4.2.7 on 2023-11-14 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("idade", models.IntegerField(default=0)),
                ("matricula", models.CharField(max_length=100)),
                ("foto", models.ImageField(upload_to="foto-aluno")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "qrcode",
                    models.ImageField(blank=True, editable=False, upload_to="qrcode"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alunos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
