# Generated by Django 4.2.7 on 2023-11-19 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="horario_entrada",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="horario_saida",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="telefone_responsavel",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aluno",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 19, 22, 4, 41, 616896, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
