# Generated by Django 4.2.7 on 2023-11-19 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_aluno_horario_entrada_aluno_horario_saida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
