# Generated by Django 4.2.7 on 2023-11-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0003_alter_aluno_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="matricula",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
