# Generated by Django 4.2.7 on 2023-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0004_alter_aluno_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="horario_entrada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="horario_saida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
