# Generated by Django 4.2.7 on 2023-11-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0005_alter_aluno_horario_entrada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="advertencias",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aluno",
            name="liberado",
            field=models.BooleanField(default=False),
        ),
    ]
