# Generated by Django 4.2.7 on 2023-12-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0006_aluno_advertencias_aluno_liberado"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
